# -*- coding: utf-8 -*-
"""Digit recognition using mnist data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMWqmwSguCBlPGELh791uZmEhz1qigz-

mnist stands for modified national institute of standards and technology database.
it has 70000 grayscale images of hand written digits(0-9):60000 for traning,10000 for testing.
image sizes 28x28 pixels.
pixel values are between 0-255.
Our task is to classify the 10 digits and identify which digit is in the image.
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

(X_train,Y_train),(X_test,Y_test)=keras.datasets.mnist.load_data()
X_train,X_test=X_train/255.0,X_test/255.0

X_train=X_train.reshape(-1,28,28,1)
X_test=X_test.reshape(-1,28,28,1)

print("training set shape:",X_train.shape)
print("testing set shape:",X_test.shape)

model=keras.Sequential([
    keras.layers.Conv2D(32,(3,3),activation="relu",input_shape=(28,28,1)),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Conv2D(64,(3,3),activation="relu"),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Flatten(),

    keras.layers.Dense(128,activation="relu"),

    keras.layers.Dense(10,activation="softmax"),

])

model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.summary()

history=model.fit(X_train, Y_train, epochs=5, validation_data=(X_test, Y_test))

test_loss, test_acc=model.evaluate(X_test,Y_test)
print(f"test accuracy:{test_acc:.2f}")

random_idx=np.random.randint(0,len(X_test))
test_image=X_test[random_idx].reshape(1,28,28,1)
prediction=model.predict(test_image)
predicted_digit=np.argmax(prediction)

plt.imshow(X_test[random_idx].reshape(28,28),cmap="gray")

plt.title(f"predicted digit:{predicted_digit}")
plt.show()